const cats = [
  {
    id: 1,
    thumbnail: '/images/1_300_200.jpg',
    name: 'Kitty Purry',
    address: '123 Purr Place',
    numWhiskers: 12,
    age: 'Senior',
    personality: 'Playful',
  },
  {
    id: 2,
    thumbnail: '/images/2_300_200.jpg',
    name: 'Fleas Witherspoon',
    address: '999 Paw Place',
    numWhiskers: 16,
    age: 'Kitten',
    personality: 'Lazy',
  },
  {
    id: 3,
    thumbnail: '/images/3_300_200.jpg',
    name: 'Cat Damon',
    address: '3412 Lazy Ln',
    numWhiskers: 4,
    age: 'Adult',
    personality: 'Cuddly',
  },
  {
    id: 4,
    thumbnail: '/images/4_300_200.jpg',
    name: 'Jude Paw',
    address: '8888 Sphynx St',
    numWhiskers: 12,
    age: 'Young',
    personality: 'Lazy',
  },
  {
    id: 5,
    thumbnail: '/images/5_300_200.jpg',
    name: 'Puma Thurman',
    address: '321 Whisker Way',
    numWhiskers: 0,
    age: 'Kitten',
    personality: 'Cuddly',
  },
  {
    id: 6,
    thumbnail: '/images/6_300_200.jpg',
    name: 'Bing Clawsby',
    address: '789 Siamese St',
    numWhiskers: 20,
    age: 'Adult',
    personality: 'Playful',
  },
  {
    id: 7,
    thumbnail: '/images/7_300_200.jpg',
    name: 'Paw McCartney',
    address: '567 Paw Place',
    numWhiskers: 12,
    age: 'Kitten',
    personality: 'Mischievous',
  },
  {
    id: 8,
    thumbnail: '/images/8_300_200.jpg',
    name: 'David Meowie',
    address: '198 Mouse Manor',
    numWhiskers: 16,
    age: 'Kitten',
    personality: 'Playful',
  },
  {
    id: 9,
    thumbnail: '/images/9_300_200.jpg',
    name: 'Catalie Portman',
    address: '222 Cat Ct',
    numWhiskers: 24,
    age: 'Young',
    personality: 'Mischievous',
  },
  {
    id: 10,
    thumbnail: '/images/10_300_200.jpg',
    name: 'Pawdrey Hepburn',
    address: '321 Garfield Glen',
    numWhiskers: 8,
    age: 'Adult',
    personality: 'Cuddly',
  },
  {
    id: 11,
    thumbnail: '/images/11_300_200.jpg',
    name: 'Bob Meowerly',
    address: '765 Persian Pkwy',
    numWhiskers: 12,
    age: 'Kitten',
    personality: 'Mischievous',
  },
  {
    id: 12,
    thumbnail: '/images/12_300_200.jpg',
    name: 'Opurrah Whisker',
    address: '391 Burmese Blvd',
    numWhiskers: 12,
    age: 'Senior',
    personality: 'Lazy',
  },
  {
    id: 13,
    thumbnail: '/images/13_300_200.jpg',
    name: 'Don Drapurr',
    address: '151 Litter Ln',
    numWhiskers: 12,
    age: 'Adult',
    personality: 'Mischievous',
  },
  {
    id: 14,
    thumbnail: '/images/14_300_200.jpg',
    name: 'Cleo Catra',
    address: '555 Purr Pkwy',
    numWhiskers: 16,
    age: 'Kitten',
    personality: 'Playful',
  },
  {
    id: 15,
    thumbnail: '/images/15_300_200.jpg',
    name: 'Emily Lickinson',
    address: '543 Tabby Trail',
    numWhiskers: 8,
    age: 'Young',
    personality: 'Mischievous',
  },
  {
    id: 16,
    thumbnail: '/images/16_300_200.jpg',
    name: 'Margaret Scratcher',
    address: '678 Adoption Alley',
    numWhiskers: 4,
    age: 'Kitten',
    personality: 'Cuddly',
  },
  {
    id: 17,
    thumbnail: '/images/1_300_200.jpg',
    name: 'Franz Catka',
    address: '319 Pounce Pkwy',
    numWhiskers: 9,
    age: 'Adult',
    personality: 'Lazy',
  },
  {
    id: 18,
    thumbnail: '/images/2_300_200.jpg',
    name: 'Leonardo DiCatrio',
    address: '444 Tiger Trail',
    numWhiskers: 15,
    age: 'Adult',
    personality: 'Cuddly',
  },
  {
    id: 19,
    thumbnail: '/images/3_300_200.jpg',
    name: 'Ryan Fleacrest',
    address: '611 Siamese St',
    numWhiskers: 13,
    age: 'Senior',
    personality: 'Mischievous',
  },
];

exports.cats = cats;
